version: '3.1'

volumes:
  pg_data:
  static:

services:
  db:
    image: postgres:latest
    env_file: .env
    ports:
    - "${POSTGRES_PORT}:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
  backend:
    build: ./backend/
    env_file: .env
    volumes:
      - static:/backend_static
  frontend:
    build: ./frontend/
    volumes:
      - static:/frontend_static
  nginx:
    image: nginx:1.19.3
    ports:
      - "80:80"
    volumes:
      - ./infra/nginx.conf:/etc/nginx/conf.d/default.conf
      - static:/frontend_static
      - ./docs/:/usr/share/nginx/html/api/docs/