version: '3.1'

volumes:
  pg_data:
  static:

services:
  db:
    image: postgres:latest
    env_file: .env
    ports:
    - "${POSTGRES_PORT}:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
  backend:
    build: ./backend/
    env_file: .env
    command: sh -c "python manage.py collectstatic --noinput && gunicorn --bind 0.0.0.0:8000 foodgram_main.wsgi:application"
    volumes:
      - static:/app/collected_static
    ports:
      - "8000:8000"
  frontend:
    build: ./frontend/
    volumes:
      - static:/app/front_static
  nginx:
    build: ./infra/
    environment:
      - STATIC_PATH=${NGINX_STATIC_PATH}
    ports:
      - "80:80"
    volumes:
      - static:/${NGINX_STATIC_PATH}